name: Main workflow
on: [push]

jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
        php-versions: ['8.0', '8.1', '8.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install deps
        run: npm install
        
      - name: Build PHP
        run: node index.js direct-workflow ${{ matrix.php-versions }}

      - name: Testing PHP version
        run: |
          php -v
          php -r "if(strpos(phpversion(), '${{ matrix.php-versions }}') === false) {throw new Exception('Wrong PHP version Installed');}"
